import { resolve, dirname } from "path";
import { fileURLToPath } from "url";
import fs from "node:fs";
import { defineConfig, Plugin } from "vite";
import vue from "@vitejs/plugin-vue";
import electron from "vite-plugin-electron/simple";
import electronPreload from "vite-plugin-electron";
import root_package from "../package.json";
import workspace_package from "./package.json";
import { allEntries, entryTitle } from "./lib/windows";

const external = Object.keys({
    ...(root_package.dependencies ?? {}),
    ...(workspace_package.dependencies ?? {}),
}) as string[];

// Externalize the native/runtime deps AND their subpaths (e.g. `core/Aravis`,
// `core/Vision`). Exact-string `external` misses subpaths, so the bundler would
// inline `core`'s loader — whose internal `require("./index.cjs")` then resolves
// against the bundle's directory (`.dist/electron`) instead of `core/dist`,
// crashing the orchestrator with MODULE_NOT_FOUND.
const isExternal = (id: string) =>
    external.some((e) => id === e || id.startsWith(`${e}/`));

const target = resolve(
    fileURLToPath(import.meta.url),
    "..",
    ".dist",
    "electron"
);

// HMR boundary (docs/history/refactor/multi-window.md req. 8 / §4). The danger class
// is stateful singletons and shared wire code: `lib/orchestrator/**` (Channel,
// the module-level `connect()` channel promise, shm read pool, protocol types
// compiled into BOTH renderer and orchestrator bundles), `lib/store.ts`, and
// module `contract.ts` files. Hot-swapping any of these in a renderer while
// the orchestrator keeps running old code = wire mismatch, duplicated
// subscriptions, leaked ports/pools. Vue HMR would happily re-execute them as
// a dep of a self-accepting SFC — so any hot update whose invalidation chain
// REACHES one of these modules (walked via the module graph's importers)
// escalates to a full page reload instead. Plain SFC/UI edits keep
// hot-reloading as before. (Protocol edits additionally rebuild the
// orchestrator via vite-plugin-electron's watch → Electron restarts → the
// reload converges with the dev restart+restore flow.)
const isProtocolLayer = (file: string): boolean =>
    /\/lib\/orchestrator\//.test(file) ||
    /\/lib\/store\.ts$/.test(file) ||
    /\/contract\.ts$/.test(file);

const hmrBoundary = (): Plugin => ({
    name: "fovea:hmr-boundary",
    apply: "serve",
    handleHotUpdate(ctx) {
        // Walk the changed modules' importer closure: a protocol-layer module
        // anywhere in the propagation path (including the changed file
        // itself) means this update cannot be safely hot-applied.
        const seen = new Set<unknown>();
        const stack = [...ctx.modules];
        let hit = isProtocolLayer(ctx.file) ? ctx.file : null;
        while (!hit && stack.length > 0) {
            const mod = stack.pop()!;
            if (seen.has(mod)) continue;
            seen.add(mod);
            if (mod.file && isProtocolLayer(mod.file)) {
                hit = mod.file;
                break;
            }
            stack.push(...mod.importers);
        }
        if (!hit) return; // normal HMR
        ctx.server.config.logger.info(
            `[hmr-boundary] full reload — protocol-layer module in update path: ${hit}`
        );
        ctx.server.ws.send({ type: "full-reload" });
        return []; // stop HMR propagation for this update
    },
});

// Window entry-HTML generator (A-27). The ~16 windows/*.html files were near-
// identical — same head/body/reset, differing only in <title> and the boot
// script — and each shipped with a one-line src/windows/<name>.ts entry. Both
// are now GENERATED from the `@lib/windows` registry: adding a window = one
// registry row. The 16 hand-written HTML + 6 boot one-liners are deleted; this
// plugin re-emits the HTML (title from the registry, one inlined module script
// that calls `bootEntry(<key>)`) on every `buildStart`, which fires for both
// `serve` and `build` before rollup loads the inputs / before the dev server
// responds. Generated files are gitignored; `rollupOptions.input`, the main-
// process URL loading, and `appIdFromPathname` all keep pointing at the same
// `windows/<key>.html` paths — they simply become generated.
const GEN_HEADER =
    "<!-- GENERATED by foveaWindowEntries — do not edit; source: lib/windows.ts -->";

function renderEntryHtml(key: string, title: string): string {
    return `<!doctype html>
${GEN_HEADER}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${title}</title>
    <style>
      * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
      }
      /* No visible scroll bar */
      ::-webkit-scrollbar {
        display: none;
      }
    </style>
  </head>
  <body oncontextmenu="return false;" style="background-color: black">
    <div id="app"></div>
    <script type="module">
      import { bootEntry } from "/src/windows/boot-entry.ts";
      bootEntry(${JSON.stringify(key)});
    </script>
  </body>
</html>
`;
}

const foveaWindowEntries = (root: string): Plugin => ({
    name: "fovea:window-entries",
    buildStart() {
        for (const [key, relPath] of Object.entries(allEntries())) {
            const file = resolve(root, relPath);
            fs.mkdirSync(dirname(file), { recursive: true });
            fs.writeFileSync(file, renderEntryHtml(key, entryTitle(key)));
        }
    },
});

// https://vitejs.dev/config/
export default defineConfig(({ command }) => {
    fs.rmSync(target, { recursive: true, force: true });
    const isServe = command === "serve";
    const isBuild = command === "build";
    const sourcemap = isServe || !!process.env.VSCODE_DEBUG;
    const PROJECT_ROOT = resolve(fileURLToPath(import.meta.url), "..");
    console.log("External Modules:", external);

    // Shared path aliases. Applied to both the renderer and the Node (main +
    // orchestrator) build so orchestrator code can reuse the pure-compute libs
    // under `@lib` (pid, stereo, geometry, vergence, ...) without relocating them.
    const alias = {
        "@": resolve(PROJECT_ROOT, "src"),
        "@lib": resolve(PROJECT_ROOT, "lib"),
        "@src": resolve(PROJECT_ROOT, "src"),
        "@modules": resolve(PROJECT_ROOT, "modules"),
        "@orchestrator": resolve(PROJECT_ROOT, "orchestrator"),
    };

    return {
        plugins: [
            foveaWindowEntries(PROJECT_ROOT),
            hmrBoundary(),
            vue(),
            electron({
                main: {
                    // Shortcut of `build.lib.entry`. The orchestrator is a
                    // second Node entry built alongside main; the main process
                    // forks it as a utilityProcess (.dist/electron/orchestrator.js).
                    // `vision-worker` (A-28) is C's per-session vision worker_thread,
                    // bundled the SAME way as the orchestrator — the shared
                    // `rollupOptions.external: isExternal` below externalizes `core`
                    // + native `.node` for it identically (the worker does
                    // `require("core")` / core/Vision + core/Tracker at runtime and
                    // loads the shm-reader addon via a parent-passed absolute path).
                    entry: {
                        main: "electron/main.ts",
                        orchestrator: "orchestrator/index.ts",
                        "vision-worker": "orchestrator/vision-worker.ts",
                        // Hardware-safety failsafe: forked by main whenever
                        // the orchestrator dies without confirming quiescence
                        // (MEMS disable + camera acquisition stop).
                        janitor: "orchestrator/janitor.ts",
                    },
                    vite: {
                        resolve: { alias },
                        build: {
                            sourcemap,
                            minify: isBuild,
                            outDir: target,
                            // Some third-party Node.js libraries may not be built correctly by Vite, especially `C/C++` addons,
                            // we can use `external` to exclude them to ensure they work correctly.
                            // Others need to put them in `dependencies` to ensure they are collected into `app.asar` after the app is built.
                            // Of course, this is not absolute, just this way is relatively simple. :)
                            rollupOptions: { external: isExternal },
                        },
                    },
                },
                // Ployfill the Electron and Node.js API for Renderer process.
                // If you want use Node.js in Renderer process, the `nodeIntegration` needs to be enabled in the Main process.
                // See 👉 https://github.com/electron-vite/vite-plugin-electron-renderer
                renderer: {
                    resolve: {
                        ...Object.fromEntries(
                            external.map((m) => [m, { type: "cjs" }])
                        ),
                    },
                },
            }),
            // Preload entries build via the low-level plugin: ONE BUILD PER
            // ENTRY, so modules shared between preloads (preload-bridge.ts)
            // are inlined into each output instead of split into a sibling
            // chunk — sandboxed preloads cannot require sibling chunks (V11).
            // Output is CJS named .cjs: unsandboxed preloads load .mjs as
            // real ESM where bare `require` throws (V11b).
            electronPreload(
                ["preload-renderer", "preload-profiler"].map((name) => ({
                    // Preload change → reload pages; never args.startup()
                    // here (the simple() plugin above owns the Electron
                    // process — a second startup would double-launch).
                    onstart: (args) => args.reload(),
                    vite: {
                        resolve: { alias },
                        build: {
                            sourcemap: sourcemap ? "inline" : undefined, // #332
                            minify: isBuild,
                            outDir: target,
                            // Explicit lib config: the plugin otherwise
                            // derives formats from package `type` (module →
                            // "es"), emitting ESM into a .cjs file — V11b
                            // all over again, one layer down.
                            lib: {
                                entry: { [name]: `electron/${name}.ts` },
                                formats: ["cjs"],
                                fileName: () => `${name}.cjs`,
                            },
                            rollupOptions: { external: isExternal },
                        },
                    },
                }))
            ),
        ],
        server:
            process.env.VSCODE_DEBUG &&
            (() => {
                const url = new URL(process.env.VITE_DEV_SERVER_URL);
                return {
                    host: url.hostname,
                    port: +url.port,
                };
            })(),
        clearScreen: false,
        optimizeDeps: {
            exclude: external,
        },
        resolve: { alias },
        build: {
            outDir: resolve(PROJECT_ROOT, ".dist", "renderer"),
            // Multi-entry renderer (docs/history/refactor/multi-window.md req. 2):
            // one entry HTML per window class/app from the `@lib/windows`
            // catalog. The legacy single-window index.html was removed in
            // Stage 5 round 2 (A-10c) — every window is a windows/* entry.
            // Renderer entries MAY share chunks — they're http/file-served
            // pages; the V11 one-build-per-entry rule applies to preloads
            // only.
            rollupOptions: {
                input: Object.fromEntries(
                    Object.entries(allEntries()).map(([name, entry]) => [
                        name,
                        resolve(PROJECT_ROOT, entry),
                    ])
                ),
            },
        },
    };
});
