// auto-nav.ts — auto-generated navbar/sidebar + live-in-dev watch plugin.
//
// The pure tree-scan lives in ./nav-core.mjs (plain ESM so it is unit-testable
// with `node docs/.vitepress/auto-nav.test.mjs`). This module is the TypeScript
// façade the VitePress config consumes: it re-exports the scan and adds the Vite
// dev-server watch plugin.
//
// ── WATCH MECHANISM (approach chosen + why it works with VitePress 1.6) ─────────
// VitePress derives themeConfig.nav / themeConfig.sidebar ONCE, when it resolves
// the user config. In dev it re-resolves the config (recreateServer) only when a
// file in `configDeps` changes — proven in node_modules/vitepress/dist/node/
// chunk-*.js:
//     handleHotUpdate(ctx) {
//       if (file === configPath || configDeps.includes(file)) { … recreateServer() }
//     }
// and, for structural changes, onFileAddDelete() re-runs resolvePages() (updating
// ROUTES) but NOT the user config — so nav/sidebar would stay stale on add/unlink.
//
// A plain Vite `server.restart()` is the WRONG lever: it restarts Vite but keeps
// the already-resolved VitePress siteConfig, so the sidebar would not refresh.
//
// So we reuse VitePress's OWN config-reload path: config.ts imports ./nav-trigger
// (making it a configDep); this plugin watches the docs tree and, on any
// structural change (.md add/unlink/rename, or dir add/remove), rewrites
// nav-trigger.ts. That configDep change makes VitePress recreateServer() ->
// re-run config.ts -> buildAutoNav() -> emit a fresh nav + sidebar, live. This is
// honest (it triggers a real, full config reload) and needs no VitePress internals.

import fs from 'node:fs';
import type { Plugin } from 'vite';
import { buildAutoNav } from './nav-core.mjs';

export { buildAutoNav, titleCase, firstHeading, scanSectionItems } from './nav-core.mjs';

export interface AutoNavWatchOptions {
  /** Absolute path to the docs root that is scanned. */
  srcDir: string;
  /** Absolute path to the configDep sentinel we rewrite to force a reload. */
  triggerFile: string;
  /** Current stamp — passed only so config.ts's import is never tree-shaken. */
  stamp?: number;
}

/**
 * Vite plugin (dev only): watch the docs tree and force VitePress to regenerate
 * the auto-nav whenever a page is added / removed / renamed, without a manual
 * restart. See the mechanism note above.
 */
export function autoNavWatch(opts: AutoNavWatchOptions): Plugin {
  const srcDirNorm = opts.srcDir.split('\\').join('/');
  let timer: NodeJS.Timeout | null = null;

  const touchTrigger = () => {
    if (timer) return; // debounce a burst of fs events into one reload
    timer = setTimeout(() => {
      timer = null;
      try {
        const stamp = Date.now();
        fs.writeFileSync(
          opts.triggerFile,
          '// AUTO-GENERATED by auto-nav watch — DO NOT EDIT. See nav-trigger.ts docstring.\n' +
            `export const NAV_TRIGGER_STAMP = ${stamp};\n`,
        );
      } catch {
        /* best-effort: a failed touch just means the user restarts manually */
      }
    }, 150);
  };

  const isDocMarkdown = (file: string) => {
    const f = file.split('\\').join('/');
    return (
      f.startsWith(srcDirNorm + '/') &&
      !f.includes('/.vitepress/') &&
      f.toLowerCase().endsWith('.md')
    );
  };
  const isDocDir = (file: string) => {
    const f = file.split('\\').join('/');
    return f.startsWith(srcDirNorm + '/') && !f.includes('/.vitepress');
  };

  return {
    name: 'foveacam:auto-nav-watch',
    apply: 'serve',
    configureServer(server) {
      const onFile = (file: string) => { if (isDocMarkdown(file)) touchTrigger(); };
      const onDir = (file: string) => { if (isDocDir(file)) touchTrigger(); };
      server.watcher
        .on('add', onFile)
        .on('unlink', onFile)
        .on('addDir', onDir)
        .on('unlinkDir', onDir);
      server.config.logger.info('[auto-nav] watching docs tree for structural changes (live nav/sidebar).');
    },
  };
}
